# Generated by Django 2.1.3 on 2020-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_code',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
