# Generated by Django 2.1.3 on 2020-04-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_personal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personal_code',
        ),
    ]
