# Generated by Django 2.1.3 on 2020-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_personal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='personal_code',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='public_code',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
