# Generated by Django 2.1.3 on 2020-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200430_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_code',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_code',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
