# Generated by Django 3.2.5 on 2021-07-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200504_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public_code',
        ),
    ]
