# Generated by Django 3.2.5 on 2021-07-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210721_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twohand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist',
            field=models.IntegerField(default=0),
        ),
    ]
