# Generated by Django 3.2.5 on 2021-07-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0002_auto_20210712_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoHand0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('a_value', models.FloatField(default=0)),
                ('v_value', models.FloatField(default=0)),
                ('r_value', models.FloatField(default=0)),
                ('temp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwoHand1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('a_value', models.FloatField(default=0)),
                ('v_value', models.FloatField(default=0)),
                ('r_value', models.FloatField(default=0)),
                ('temp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwoHand2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('a_value', models.FloatField(default=0)),
                ('v_value', models.FloatField(default=0)),
                ('r_value', models.FloatField(default=0)),
                ('temp', models.IntegerField(default=0)),
            ],
        ),
    ]
