# Generated by Django 3.2.5 on 2021-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0003_twohand0_twohand1_twohand2'),
    ]

    operations = [
        migrations.AddField(
            model_name='twohand0',
            name='a_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand0',
            name='r_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand0',
            name='v_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand1',
            name='a_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand1',
            name='r_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand1',
            name='v_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand2',
            name='a_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand2',
            name='r_motion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twohand2',
            name='v_motion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
