# Generated by Django 3.2.5 on 2021-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0004_auto_20210728_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('a_motion', models.CharField(default='', max_length=50)),
                ('v_motion', models.CharField(default='', max_length=50)),
                ('r_motion', models.CharField(default='', max_length=50)),
                ('exercise', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
